name = "Not Adrenaserver"
author = "Uranite"
version = "1.0.0+1.21.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e70ca393d84aadd058b465b1f7451867ab70e68517aa796572278d20f66439f2"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
