name = "Not Adrenaserver"
author = "Uranite"
version = "1.0.0+1.21.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d1a634daa655765e82cb3e22072da5dbdc208d26f42fd2f6db3af4c3bcdfff0"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
