name = "Adrenaserver"
author = "UltraStorm"
version = "1.3.1+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aaf9837ea67cd715baa34af16527f8211f625d585bfcfd34ec612f0eac1bfe8e"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
