name = "Adrenaserver"
author = "UltraStorm"
version = "1.2.3+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3efd2ba8ee498dfde0e4a3c3daa1072fbcbb9d9282a7eeb6ca8fe567e587b43a"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
