name = "Adrenaserver"
author = "UltraStorm"
version = "1.4.0+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "533a59fc05469529e43b4ac1018578c0a8fac3dd27bd035373bf17c57a09b851"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
