name = "Adrenaserver"
author = "getchoo"
version = "1.5.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0d535778bb9ebfbf7097a2d57b5512be48dfd093ad5b9464ab06b81a4171bba"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
