name = "Adrenaserver"
author = "getchoo"
version = "1.6.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f35179b5409055037bd74507ba1d0fec0ad83564c114141002e23dd5d7a8d07"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
