name = "Adrenaserver"
author = "UltraStorm"
version = "1.2.0+1.17.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "048399c2628723597d8416d5285b4c3764b55ce12da0ce8aa6e99a1230640193"

[versions]
fabric = "0.14.13"
minecraft = "1.17.1"
