name = "Adrenaserver Fork"
author = "Yiss"
version = "1.0.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6ade78e7de7d7fd610e503dcd76f064a64268e5e2ac6ea16ae24426e19e0a17"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
