name = "Adrenaserver"
author = "UltraStorm"
version = "1.4.0+1.20.1.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32fdc0b8444650c84be160983ca6c329041552a9f37a14f2e35281be970eeee3"

[versions]
minecraft = "1.20.1"
quilt = "0.19.1"
