name = "Adrenaserver"
author = "getchoo"
version = "1.5.0+1.20.1.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cbc48a6bf73499fc326321c360b3bb111d0b396a70e8c7a785ca7e730b3d43c"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
