name = "Adrenaserver Fork"
author = "Yiss"
version = "1.0.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12affec2962338030b91de5785c36ca84900c3d0c8c3b639ebaa61faeabcb4a0"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
