name = "Badly Optimized"
author = "Yiss"
version = "1.0.0+26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f927799474a9c0525ca0fb7ee33bde093359dcfb57796e1389ab980c8d880476"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
