name = "Adrenaserver"
author = "UltraStorm"
version = "1.4.0+1.19.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afe06279304c89940f37e219af765b8e10b823653b49ed78655d7d2a8672ed7d"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
