name = "Adrenaserver"
author = "UltraStorm"
version = "1.2.1+1.19.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2dfa0cd033f4aab508496279ce4dab32ea063f90ab18f428232881653e1f4afd"

[versions]
fabric = "0.14.14"
minecraft = "1.19.2"
