name = "Adrenaserver"
author = "UltraStorm"
version = "1.2.3+1.19.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47f803d772b80c91c13f8d5563ebe6b5a4d124c14e318f9e595d27b5d726e22d"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
