name = "Adrenaserver"
author = "getchoo"
version = "1.4.1+1.19.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1df5fc807bb28ffdfdb4762e64b06cb1dc7bef5c241c5b63f701407db4ce6e9"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
