name = "Adrenaserver"
author = "UltraStorm"
version = "1.2.4+1.19.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3d5cf28efbdfa26d64c8771a489e76d2d254fece0ccd688caf0f5c82be12cdf"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
