name = "Adrenaserverfork"
author = "yiss"
version = "1.0.0+1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad14ce70afea95c390d5410890777886fb820bb1226b9f905c99ac8cf1cc6498"

[versions]
fabric = "0.18.0"
minecraft = "1.21.10"
