name = "Adrenaserverfork"
author = "yiss"
version = "1.0.0+1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fafe19f5ddc5d2efd19280a126b62b3797cd7cde86efb76920028a52587ae1b2"

[versions]
fabric = "0.18.0"
minecraft = "1.21.10"
