name = "Adrenaserver"
author = "getchoo"
version = "1.4.1+1.20.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8de826bd9f5f9be688ca512d304338188e8ddcbba9730638ae68100e9d536115"

[versions]
fabric = "0.14.22"
minecraft = "1.20.2"
