name = "Adrenaserverfork"
author = "yiss"
version = "1.0.0+1.21.8.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8cc2318b74b819e97b30b18c23339b29f22422bf8675a2d5542a529c4cfbbe4"

[versions]
fabric = "0.18.0"
minecraft = "1.21.8"
