name = "Adrenaserverfork"
author = "yiss"
version = "1.0.0+1.21.8.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2acbc5b2b6a9021873d1ba1a0d741887b1a5eb63a9be5a0144b8f16344b45eb3"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
