name = "Adrenaserverfork"
author = "yiss"
version = "1.0.0+1.21.8.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2939463beab5e6cada354753bb2b3874823108ca2159e96fc3d0b41fb53a964"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
