name = "Adrenaserver"
author = "getchoo"
version = "1.5.0+1.19.4.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38b70ade754efae99469dc19f76eac64880d0e81a5f19cf83963c02d1cca0137"

[versions]
minecraft = "1.19.4"
quilt = "0.22.0"
