name = "Adrenaserver"
author = "UltraStorm"
version = "1.2.4+1.19.4.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5a77a3790fea51497051d493208b760a6eff892b623de87bae3212e0d44602a"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
