name = "Adrenaserver"
author = "UltraStorm"
version = "1.4.0+1.19.4.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d662486041352183a4e6d771ce943d12f7c2768bf65583c416f05db98bae6f1"

[versions]
minecraft = "1.19.4"
quilt = "0.19.1"
