name = "Adrenaserver"
author = "UltraStorm"
version = "1.2.4+1.18.2.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a31a630dd1d9d10b90f1e9ea7c61b611341960250fa274dfce28ad818747c68f"

[versions]
minecraft = "1.18.2"
quilt = "0.18.10"
