name = "Adrenaserver"
author = "UltraStorm"
version = "1.4.0+1.19.2.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ebe76fa76c6162d95ee1a0c4b4f9fb6257962da4db075450339411b68e5ca65"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
