name = "Adrenaserver"
author = "UltraStorm"
version = "1.2.1+1.19.2.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e10b2695ef9b65a393c766e808f583b38fd1aadde569513474c17ddab833b2d9"

[versions]
minecraft = "1.19.2"
quilt = "0.18.2"
