name = "Adrenaserver"
author = "getchoo"
version = "1.4.1+1.19.2.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9d8a9a681ce32dd3364da4446f53e40981554f4a707452ac840db4307f92590"

[versions]
minecraft = "1.19.2"
quilt = "0.19.5"
