name = "Adrenaserver"
author = "UltraStorm"
version = "1.3.1+1.16.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edf698124b8dcb9154a14e3105deaf77e88cb8435c7e4debac8bb736b515316e"

[versions]
fabric = "0.14.21"
minecraft = "1.16.5"
