name = "Adrenaserverfork"
author = "yiss"
version = "1.0.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9f59b128255fcf25823a9e998b1a21f1323547dd81996131338ba0f39d843fb"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
