name = "Adrenaserverfork"
author = "yiss"
version = "1.0.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aaf512a2d48491d275e5ca0cd5c75d6ba44f05b2b86191800da2ae3f638c7644"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
