name = "Adrenaserver"
author = "UltraStorm"
version = "1.2.0+1.18.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "634eeb49a835079cb8b6879ec8669fdc9f7badef0dd7d37f89e521e43a0f3b73"

[versions]
fabric = "0.14.13"
minecraft = "1.18.2"
