name = "Adrenaserver"
author = "UltraStorm"
version = "1.2.3+1.19.3.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "835c63aeddc83b0235e282135fe66536afae833abb21595cd0e2d592c4056815"

[versions]
minecraft = "1.19.3"
quilt = "0.18.6"
