name = "Adrenaserver"
author = "UltraStorm"
version = "1.2.0+1.19.3.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c2209a07fb36d8af2ba78869cfcd4c85a01a59e18508285e351ae1512ae9d40"

[versions]
minecraft = "1.19.3"
quilt = "0.17.10"
