name = "Adrenaserver"
author = "UltraStorm"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e08289bc116fb0153fcd57812a26c350c229a7e198a01dc8593720f4b81d0ff0"

[versions]
minecraft = "1.19.3"
quilt = "0.17.7"
