name = "Adrenaserver"
author = "UltraStorm"
version = "1.2.1+1.19.3.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1643ef1a4bacdd629eaa3e9bda8eb7e5bec9b670475f30c0dcf3c5e9c8ccf70"

[versions]
minecraft = "1.19.3"
quilt = "0.18.2"
