name = "Adrenaserver"
author = "UltraStorm"
version = "1.3.0+1.20.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84bf54a165e88b5d469e60bfae446460d9833612e80cc68c63b42d4649282ddc"

[versions]
fabric = "0.14.21"
minecraft = "1.20"
